export const SHOW_LOADING_COMPONENT = Symbol('SHOW_LOADING_COMPONENT');
export const HIDE_LOADING_COMPONENT = Symbol('HIDE_LOADING_COMPONENT');
export const RENDER_CONTENT = Symbol('RENDER_CONTENT');
