export const SHOW_LOADING_COMPONENT = Symbol('SHOW_LOADING_COMPONENT');
export const HIDE_LOADING_COMPONENT = Symbol('HIDE_LOADING_COMPONENT');
export const RENDER_CONTENT = Symbol('RENDER_CONTENT');
export const FETCH_ERROR = Symbol('FETCH_ERROR');
export const UNIT_CHANGE = Symbol('UNIT_CHANGE');
export const USE_MY_LOCATION_REQUESTED = Symbol('USE_MY_LOCATION_REQUESTED');
export const SEARCH_LOCATION = Symbol('SEARCH_LOCATION');
export const SHOW_SEARCH_LOADING_COMPONENT = Symbol(
  'SHOW_SEARCH_LOADING_COMPONENT',
);
export const HIDE_SEARCH_LOADING_COMPONENT = Symbol(
  'HIDE_SEARCH_LOADING_COMPONENT',
);
export const SHOW_SEARCH_LOCATION_RESULT = Symbol('SEARCH_LOCATION_RESULT');
export const FETCH_SELECTED_LOCATION = Symbol('FETCH_SELECTED_LOCATION');
