export const SHOW_LOADING_COMPONENT = Symbol('SHOW_LOADING_COMPONENT');
export const HIDE_LOADING_COMPONENT = Symbol('HIDE_LOADING_COMPONENT');
export const RENDER_CONTENT = Symbol('RENDER_CONTENT');
export const FETCH_ERROR = Symbol('FETCH_ERROR');
export const UNIT_CHANGE = Symbol('UNIT_CHANGE');
